"""Add package_provider, chat, and blog models

Revision ID: 0ad82e3efb48
Revises: 65e34926728d
Create Date: 2026-09-13 22:59:52.713916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ad82e3efb48'
down_revision: Union[str, Sequence[str], None] = '65e34926728d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('traveler_id', sa.BigInteger(), nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'planner_id', name='uq_chat_room_traveler_planner')
    )
    op.create_index('ix_chat_room_planner', 'chat_rooms', ['planner_id'], unique=False)
    op.create_index('ix_chat_room_traveler', 'chat_rooms', ['traveler_id'], unique=False)
    op.create_table('destination_blogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blog_author', 'destination_blogs', ['author_id'], unique=False)
    op.create_index('ix_blog_destination', 'destination_blogs', ['destination_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_msg_created', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_msg_room', 'chat_messages', ['room_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('traveler', 'planner', 'admin', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('traveler', 'planner', 'package_provider', 'admin', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('traveler', 'planner', 'package_provider', 'admin', name='userrole'),
               type_=mysql.ENUM('traveler', 'planner', 'admin', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index('ix_chat_msg_room', table_name='chat_messages')
    op.drop_index('ix_chat_msg_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_blog_destination', table_name='destination_blogs')
    op.drop_index('ix_blog_author', table_name='destination_blogs')
    op.drop_table('destination_blogs')
    op.drop_index('ix_chat_room_traveler', table_name='chat_rooms')
    op.drop_index('ix_chat_room_planner', table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
