"""initial travel planner database

Revision ID: 65e34926728d
Revises: 
Create Date: 2026-09-10 18:19:31.278523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e34926728d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=200), nullable=True),
    sa.Column('average_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('traveler', 'planner', 'admin', name='userrole'), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_trips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('traveler_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_name', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('travelers_count', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('generated_itinerary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_trips_traveler_id'), 'ai_trips', ['traveler_id'], unique=False)
    op.create_index('ix_aitrip_traveler', 'ai_trips', ['traveler_id'], unique=False)
    op.create_table('planner_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('starting_price', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_profiles_user_id'), 'planner_profiles', ['user_id'], unique=True)
    op.create_table('trip_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('traveler_id', sa.BigInteger(), nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('travelers_count', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('travel_style', sa.String(length=100), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'in_progress', 'completed', 'cancelled', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tr_status', 'trip_requests', ['status'], unique=False)
    op.create_index(op.f('ix_trip_requests_planner_id'), 'trip_requests', ['planner_id'], unique=False)
    op.create_index(op.f('ix_trip_requests_traveler_id'), 'trip_requests', ['traveler_id'], unique=False)
    op.create_table('planner_destinations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planner_id'], ['planner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planner_id', 'destination_id', name='uq_planner_destination')
    )
    op.create_index('ix_pd_destination', 'planner_destinations', ['destination_id'], unique=False)
    op.create_index('ix_pd_planner', 'planner_destinations', ['planner_id'], unique=False)
    op.create_table('travel_packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_travelers', sa.Integer(), nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'draft', name='packagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planner_id'], ['planner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_packages_destination_id'), 'travel_packages', ['destination_id'], unique=False)
    op.create_index(op.f('ix_travel_packages_planner_id'), 'travel_packages', ['planner_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('traveler_id', sa.BigInteger(), nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=True),
    sa.Column('package_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fav_traveler', 'favorites', ['traveler_id'], unique=False)
    op.create_index(op.f('ix_favorites_traveler_id'), 'favorites', ['traveler_id'], unique=False)
    op.create_table('package_itineraries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'day_number', name='uq_package_day')
    )
    op.create_index(op.f('ix_package_itineraries_package_id'), 'package_itineraries', ['package_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('traveler_id', sa.BigInteger(), nullable=False),
    sa.Column('planner_id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=True),
    sa.Column('trip_request_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_request_id')
    )
    op.create_index('ix_review_planner', 'reviews', ['planner_id'], unique=False)
    op.create_index(op.f('ix_reviews_planner_id'), 'reviews', ['planner_id'], unique=False)
    op.create_index(op.f('ix_reviews_traveler_id'), 'reviews', ['traveler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_traveler_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_planner_id'), table_name='reviews')
    op.drop_index('ix_review_planner', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_package_itineraries_package_id'), table_name='package_itineraries')
    op.drop_table('package_itineraries')
    op.drop_index(op.f('ix_favorites_traveler_id'), table_name='favorites')
    op.drop_index('ix_fav_traveler', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_travel_packages_planner_id'), table_name='travel_packages')
    op.drop_index(op.f('ix_travel_packages_destination_id'), table_name='travel_packages')
    op.drop_table('travel_packages')
    op.drop_index('ix_pd_planner', table_name='planner_destinations')
    op.drop_index('ix_pd_destination', table_name='planner_destinations')
    op.drop_table('planner_destinations')
    op.drop_index(op.f('ix_trip_requests_traveler_id'), table_name='trip_requests')
    op.drop_index(op.f('ix_trip_requests_planner_id'), table_name='trip_requests')
    op.drop_index('ix_tr_status', table_name='trip_requests')
    op.drop_table('trip_requests')
    op.drop_index(op.f('ix_planner_profiles_user_id'), table_name='planner_profiles')
    op.drop_table('planner_profiles')
    op.drop_index('ix_aitrip_traveler', table_name='ai_trips')
    op.drop_index(op.f('ix_ai_trips_traveler_id'), table_name='ai_trips')
    op.drop_table('ai_trips')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
